---
title: "ImpactDataViz 241 Final Project"
output:
  pdf_document: default
  github_document: default
  knit: (function(inputFile, encoding) {
    rmarkdown::render(
      inputFile, encoding = encoding,
      output_format = c('github_document', 'pdf_document')) 
      })
---

```{r}
# load packages 
library(data.table)
library(foreign)
library(sandwich)
library(stargazer)
library(lmtest)
library(tidyr)
library(knitr)
library('ggplot2')
library(fastDummies)
```


## Common functions
```{r}
# function to return confidence intervals with bust se
get_confint_robust = function(model, vcovCL) {
  t<-qt(.975, model$df.residual)
  ct<-coeftest(model, vcovCL)
  est<-cbind(ct[,1], ct[,1]-t*ct[,2], ct[,1]+t*ct[,2], ct[,4])
  colnames(est)<-c("Estimate","LowerCI","UpperCI","pValue")
  return(est)
}

# parse out the regression results using robust standard errors
get_regression_results_robust_se = function(model, df, variable_names, showAsTibble) {
  model$vcovHC = vcovHC(model,type="HC1")
  
  robust_se_all    <- sqrt(diag(model$vcovHC))
  
  est = get_confint_robust(model,model$vcovHC)

  robust_se = c(rep(0, length(variable_names)))
  i = 1
  for (variable_name in variable_names) {
    robust_se_single <- sqrt(diag( model$vcovHC))[variable_name] 
    robust_se[i] = robust_se_single
    i = i + 1
  }
  
  coef = est[variable_names, 'Estimate']
  ci_lower_robust = est[variable_names, 'LowerCI']
  ci_lower_robust = est[variable_names, 'LowerCI']
  ci_upper_robust = est[variable_names, 'UpperCI']
  p_value = est[variable_names, 'pValue']
  results = data.table(id = variable_names)
  results[, coef := round(coef,4)]
  results[, ci_lower := round(ci_lower_robust,4)]
  results[, ci_upper := round(ci_upper_robust,4)]
  results[, p_value := signif(p_value, 5)]
  results[, robust_se := round(robust_se,4)]
  
  if (showAsTibble) {
    print(as_tibble(results))
  }
  return( list('estimates'=results, 'robust_se_all'=robust_se_all))
}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

```


## 1. Parse the survey data into a data.table

```{r}

parse_survey_data = function(filename, treatment_only=FALSE) {
  cat(filename, "\n")
  raw <- fread(filename)

  # covariates
  setnames(raw, 'Q3', 'state')
  setnames(raw, 'Q4', 'gender')
  setnames(raw, 'Q5', 'age')
  setnames(raw, 'Q6', 'ethnicity_multi')
  setnames(raw, 'Q7', 'political_party')
  setnames(raw, 'Q8', 'education')
  setnames(raw, 'Q9', 'covid_sick')
  setnames(raw, 'Q10', 'covid_hospitalized')
  setnames(raw, 'Q11', 'covid_died')
  
  # duration of survey time
  setnames(raw, 'Duration (in seconds)', 'duration_of_survey')
  
  # which block was active? (did the user see the treatment or 
  # control data viz) 
  setnames(raw, 'Q15', 'treatment_viz_is_accurate')
  if (!treatment_only) {
    setnames(raw, 'Q17', 'control_viz_is_accurate')
  }
  
  # outcome questions about COVID attitudes
  setnames(raw, 'Q18', 'outcome_spread')
  setnames(raw, 'Q19', 'outcome_death')
  
  # which block was active determines if
  # subject received treatment data viz or control
  # data viz
  cat(" number of responses", nrow(raw), '\n')
  raw[, treatment := ifelse(is.na(treatment_viz_is_accurate), 0, 1)]
  cleaned = raw[!is.na(outcome_spread) & !is.na(outcome_death),]
  cat(" number of responses after dropping na", nrow(cleaned), '\n')
  
  # ethnicity allows for multiple choice
  # for covariates, just grab the first one
  ethnicity_single = rep(0,nrow(cleaned))
  i = 1
  for (eth_entry in cleaned[,ethnicity_multi]) {
    eth_tokens = unlist(strsplit(eth_entry, ","))
    ethnicity_single[i] = as.numeric(eth_tokens[1])
    i = i + 1
  }
  cleaned[, ethnicity := ethnicity_single ]
  
  
  # counts in control vs treatment
  n_control = nrow(cleaned[treatment == 0, ])
  n_treatment = nrow(cleaned[treatment == 1, ])
  
  cat(" number in treatment", n_treatment, "\n")
  cat(" number in control", n_control, "\n\n")
  
  return(cleaned)
}

```


```{r}
# A large run of 260 subjects run on 7/21
run1 <- parse_survey_data("data/run1.2020.07.21.csv")
run1 = run1[, run := 0]
run1[, condition := treatment]


# One small run was done in evening 7/24 treatment only
run2_small <- parse_survey_data("data/run2.small.2020.07.24.csv", TRUE)
run2_small[, run := 1]
run2_small[, condition := treatment]
run2_small[, control_viz_is_accurate := ""]

# A large run of 270 run on 7/25 treatment and control
run2_large <- parse_survey_data("data/run2.2020.07.25.csv")
run2_large = run2_large[, run :=1]
run2_large[, condition := treatment]
run2 = rbind(run2_small, run2_large)


# Combine the runs on 7/21 and 7/25
combined = rbind(run1, run2)
```


## 2. EDA


### 2.1 Check Duration of Survey
```{r}
show_duration = function(d) {
  cat('duration for control  ', mean(d[condition == 0,duration_of_survey]), '\n')
  cat('duration for treatment', mean(d[condition == 1,duration_of_survey]), '\n\n')
}
show_duration(run1)
show_duration(run2)
show_duration(combined)
```



## 3. Covariate balance 

### 3.1 Compare distributions using violin plote
```{r , fig.width = 8, fig.height = 12}
check_covariate_balance = function(d) {
  options(repr.plot.width = 14, repr.plot.height = 8)
  
  p1 = ggplot(d, aes(x=as.factor(condition), y=gender, fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p2 = ggplot(d, aes(x=as.factor(condition), y=age, fill=as.factor(condition))) +
    geom_violin()  +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p3 = ggplot(d, aes(x=as.factor(condition), y=as.numeric(ethnicity),  fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p4 = ggplot(d, aes(x=as.factor(condition), y=political_party,  fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p5 = ggplot(d, aes(x=as.factor(condition), y=education,  fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p6 = ggplot(d, aes(x=as.factor(condition), y=covid_sick,  fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p7 = ggplot(d, aes(x=as.factor(condition), y=covid_hospitalized,  fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
  
  p8 = ggplot(d, aes(x=as.factor(condition), y=covid_died, fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 

  p9 = ggplot(d, aes(x=as.factor(condition), y=state, fill=as.factor(condition))) +
    geom_violin() +  scale_fill_manual(values=c("#a69da0", "#f95b3a")) 
   
  multiplot(p1, p2, p3, p4, p5, p6, p7, p8, p9, cols=3)
}
check_covariate_balance(run1)
check_covariate_balance(run2)
check_covariate_balance(combined)
```


## 4. Estimate ATE


### 4.1 Estimate the ATE for both outcomes
```{r}
estimate_ate = function(d, outcome_field) {
  g <- d[ , .(group_mean = mean(get(outcome_field))), keyby = .(condition)]

  
  ate <- g[ , diff(group_mean)]

  res <- NA
  for (i in 1:10000) {
      res[i] <- d[ , .(group_mean = mean(get(outcome_field))), keyby = .(sample(condition))][ , diff(group_mean)]
  }
  dist_sharp_null <- res
  #hist(dist_sharp_null)
  #abline(v=ate, lwd=3, col='blue')
  #abline(v=abs(ate), lwd=3, col='blue')
  p_value_one_tailed <- mean(dist_sharp_null >= ate)
  p_value_two_tailed <- mean(abs(dist_sharp_null) >= abs(ate))

  
  cat(outcome_field, '\n')
  cat(' mean control    ', g[condition == '0', group_mean], '\n')
  cat(' mean treatement ', g[condition == '1', group_mean], '\n')
  cat(' ATE             ', ate, '\n')
  cat(' p_value 1-tailed', p_value_one_tailed, '\n')
  cat(' p_value 2-tailed', p_value_two_tailed, '\n\n')
}



cat('run1', '\n')
cat('********************', '\n')
estimate_ate(run1, 'outcome_spread')
estimate_ate(run1, 'outcome_death')


cat('run2', '\n')
cat('********************', '\n')
estimate_ate(run2, 'outcome_spread')
estimate_ate(run2, 'outcome_death')


cat('combined', '\n')
cat('********************', '\n')
estimate_ate(combined, 'outcome_spread')
estimate_ate(combined, 'outcome_death')


```

```{r}

meanFunction <- function(x){
return(data.frame(y=round(mean(x),2),label=round(mean(x,na.rm=T),2)))
}

show_box_plot_spread = function(df, title) {
  df$treatment_group <- as.factor(df$condition)
  p = ggplot(df, aes(x=treatment_group, y=outcome_spread, fill=treatment_group)) + geom_boxplot()  +
    scale_fill_manual(values=c("#a69da0", "#f95b3a")) + labs(title=title, x="Control vs. Treatment", y = "Concern") + scale_y_continuous(breaks=seq(0, 4, by = .2))  + stat_summary(fun.y=mean, geom = "errorbar",aes(ymax = ..y.., ymin = ..y..),
                 width = 1, linetype = "dashed") + stat_summary(fun.data = meanFunction, geom="text", size = 4, vjust=-1, hjust=4.2) 

  p + geom_jitter(shape=16, alpha=.3, position=position_jitter(0.2))
}

show_box_plot_death= function(df, title) {
  df$treatment_group <- as.factor(df$condition)
  p = ggplot(df, aes(x=treatment_group, y=outcome_death, fill=treatment_group)) + geom_boxplot()  +
    scale_fill_manual(values=c("#a69da0", "#f95b3a")) + labs(title=title, x="Control vs. Treatment", y = "Distress") + scale_y_continuous(breaks=seq(0, 4, by = .2)) + stat_summary(geom = "errorbar",aes(ymax = ..y.., ymin = ..y..),
                 width = 1, linetype = "dashed") + stat_summary(fun.data = meanFunction, geom="text", size = 4, vjust=-1, hjust=4.2) 
    
    
    #stat_summary(fun.y=mean, geom="line", shape=10, size=14, color="black", fill="red") 

  p + geom_jitter(shape=16, size=2, alpha=.3, position=position_jitter(0.2) )
}

meanFunction1 <- function(x){
return(data.frame(y=round(mean(x),0),label=round(mean(x,na.rm=T),0)))
}
show_box_plot_duration= function(df, title) {
  df$treatment_group <- as.factor(df$condition)
  p = ggplot(df, aes(x=treatment_group, y=duration_of_survey, fill=treatment_group)) + geom_boxplot()  +
    scale_fill_manual(values=c("#a69da0", "#f95b3a")) + labs(title=title, x="Control vs. Treatment", y = "Duration (seconds)")  + stat_summary(geom = "errorbar",aes(ymax = ..y.., ymin = ..y..),
                 width = 1, linetype = "dashed") + stat_summary(fun.data = meanFunction1, geom="text", size = 4, vjust=-.95, hjust=3) 

  p + geom_jitter(shape=16, size=2, alpha=.3, position=position_jitter(0.2) )
}


show_box_plot_spread(run1, "Concern over spread of COVID-19 in U.S. - Run 1")
show_box_plot_spread(run2, "Concern over spread of COVID-19 in U.S. - Run 2")
show_box_plot_spread(combined, "Concern over spread of COVID-19 in U.S. - Both Runs")


show_box_plot_death(run1, "Distress over COVID-19 deaths in U.S. - Run 1")
show_box_plot_death(run2, "Distress over COVID-19 deaths in U.S. - Run 2")
show_box_plot_death(combined, "Distress over COVID-19 deaths in U.S. - Both runs")

show_box_plot_duration(combined, "Survey Duration - Both runs")


```


```{r}
cat(combined[treatment == 0, mean(duration_of_survey)], '\n')
cat(combined[treatment == 1, mean(duration_of_survey)], '\n')

```
## 5. Linear Regression


### 5.1 Perform linear regression the two outcomens (concern about COVID-19 spread, concern about COVID-19 deaths)
```{r}


run_regression_outcome1 = function(d, control_for_run=FALSE) {
  model_spread = lm(outcome_spread ~ condition, d) 
  if (control_for_run) {
    model_spread_adv = lm(outcome_spread ~ condition 
                       + run
                       + as.factor(gender) 
                       + as.factor(age) 
                       + as.factor(ethnicity) 
                       + as.factor(political_party) 
                       + as.factor(education) 
                       + as.factor(covid_sick) 
                       + as.factor(covid_hospitalized) 
                       + as.factor(covid_died), d)
    
  } else {
    model_spread_adv = lm(outcome_spread ~ condition 
                       + as.factor(gender) 
                       + as.factor(age) 
                       + as.factor(ethnicity) 
                       + as.factor(political_party) 
                       + as.factor(education) 
                       + as.factor(covid_sick) 
                       + as.factor(covid_hospitalized) 
                       + as.factor(covid_died), d)
    
  }
  est_spread     = get_regression_results_robust_se(model_spread,  d, c('condition'), FALSE)
  est_spread_adv = get_regression_results_robust_se(model_spread_adv, d, c('condition'), FALSE)
  return ( list('model'= model_spread, 
                'model_adv'=model_spread_adv, 
                'est'=est_spread, 
                'est_adv'=est_spread_adv))
}

  

run_regression_outcome2 = function(d, control_for_run) {
  model_spread = lm(outcome_spread ~ condition, d) 
  if (control_for_run) {
    model_spread_adv = lm(outcome_death ~ condition 
                       + run
                       + as.factor(gender) 
                       + as.factor(age) 
                       + as.factor(ethnicity) 
                       + as.factor(political_party) 
                       + as.factor(education) 
                       + as.factor(covid_sick) 
                       + as.factor(covid_hospitalized) 
                       + as.factor(covid_died), d)
    
  } else {
    model_spread_adv = lm(outcome_death ~ condition 
                       + as.factor(gender) 
                       + as.factor(age) 
                       + as.factor(ethnicity) 
                       + as.factor(political_party) 
                       + as.factor(education) 
                       + as.factor(covid_sick) 
                       + as.factor(covid_hospitalized) 
                       + as.factor(covid_died), d)
    
  }
  est_spread     = get_regression_results_robust_se(model_spread,  d, c('condition'), FALSE)
  est_spread_adv = get_regression_results_robust_se(model_spread_adv, d, c('condition'), FALSE)
  return ( list('model'= model_spread, 
                'model_adv'=model_spread_adv, 
                'est'=est_spread, 
                'est_adv'=est_spread_adv))
}

aggregate_covariates = function(df) {
  df[, college_educated := ifelse(education > 4, 1, 0)]
  df[, caucasian := ifelse(ethnicity == 3, 1, 0)]
  df[, age_under_40 := ifelse(age < 4, 1, 0)]
  df[, age_40_60 := ifelse(age > 4 & age <= 6, 1, 0)]
  df[, age_over_60 := ifelse(age >= 7, 1, 0)]
  
}


```

```{r}

regression_labels_run = c('Treatment', 
      'Run',
      'Female', 'Non-binary', 'Gender not answered',
      '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', 'Over 80',
      'Black/African American', 'Caucasian', 'Hispanic/Latinx', 
        'Native American', 'Pacific Islander', 'Ethnicity not answered',
      'Democrat', 'Independent', 'Party other',
      'High school', 'Some college', 'Associates', 'Bachelors', 'Masters', 'Doctoral', 'JD/MD',
      'Sick from COVID-19', 
      'Hospitalized from COVID-19', 
      'Died COVID-19')



mi_spread_run1 = run_regression_outcome1(run1, TRUE)
mi_spread_run2 = run_regression_outcome1(run2, TRUE)
mi_spread_combined_run = run_regression_outcome1(combined, TRUE)


stargazer(mi_spread_run1$model, mi_spread_run1$model_adv, 
          mi_spread_run2$model_adv, 
          mi_spread_combined_run$model_adv,
          type="text",  
          se = list(mi_spread_run1$est$robust_se_all, mi_spread_run1$est_adv$robust_se_all,
                    mi_spread_run2$est_adv$robust_se_all,
                    mi_spread_combined_run$est_adv$robust_se_all),
          title=paste('Response to COVID-19 Spread'), 
          dep.var.caption  = "Response to COVID-19 Spread",
          dep.var.labels.include = FALSE, model.numbers=FALSE,
          column.labels = c("July 21, 2020", "July 21, 2020", "July 25, 2020", "Both dates"),
          align=TRUE,
          covariate.labels = regression_labels_run)




mi_death_run1 = run_regression_outcome2(run1, TRUE)
mi_death_run2 = run_regression_outcome2(run2, TRUE)
mi_death_combined_run = run_regression_outcome2(combined, TRUE)


stargazer(mi_death_run1$model, mi_death_run1$model_adv, 
          mi_death_run2$model_adv, 
          mi_death_combined_run$model_adv,
          type="text",
          se = list(mi_death_run1$est$robust_se_all, mi_death_run1$est_adv$robust_se_all,
                    mi_death_run2$est_adv$robust_se_all,
                    mi_death_combined_run$est_adv$robust_se_all),
          title=paste('Response to COVID-19 Death'), 
          dep.var.caption  = "Response to COVID-19 Death",
          dep.var.labels.include = FALSE, model.numbers=FALSE,
          column.labels = c("July 21, 2020", "July 21, 2020", "July 25, 2020", "Both dates"),
          align=TRUE,
          covariate.labels = regression_labels_run)



```

```{r}


state_ordinals <- fread('data/state_ordinals.csv')
states_northeast = c('Connecticut','Maine','Massachusetts','New Hampshire','Rhode Island','Vermont','New Jersey','New York','Pennsylvania')
states_midwest  = c('Illinois','Indiana','Michigan','Ohio','Wisconsin', 'Iowa', 'Kansas', 'Minnesota', 'Missouri', 'Nebraska', 'North Dakota', 'South Dakota')
states_south = c('Delaware', 'Florida', 'Georgia', 'Maryland', 'North Carolina', 'South Carolina', 'Virginia', 'District of Columbia', 'West Virginia', 'Alabama', 'Kentucky', 'Mississippi', 'Tennessee', 'Arkansas', 'Louisiana', 'Oklahoma', 'Texas')
states_west = c('Arizona', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Utah', 'Wyoming', 'Alaska', 'California', 'Hawaii', 'Oregon', 'Washington')
states_other = c('Puerto Rico')


get_region_for_state = function(ordinal) {
  state_name = state_ordinals[ordinal, V1]
  if (is.element(state_name, states_northeast)) {
    return("northeast")
  } else  if (is.element(state_name, states_midwest)) {
     return("midwest")
  } else  if (is.element(state_name, states_south)) {
    return("south")
  } else  if (is.element(state_name, states_west)) {
    return("west")
  } else  if (is.element(state_name, states_other)) {
    return ("other")
  } else {
    return("other")
  }
}
get_region_for_state(5)

regions = c(rep('',53))
i = 1
for (ordinal in state_ordinals$V2) {
  the_region = get_region_for_state(ordinal)
  cat(the_region, i, '\n')
  regions[i] = the_region
  i = i + 1
}

state_ordinals[, region:= regions]

state_ordinals
  
  
  


```

```{r}


aggregate_covariates = function(df) {
  df[, gender_male := ifelse(gender == 1, 1, 0)]
  df[, gender_female := ifelse(gender == 2, 1, 0)]
  df[, gender_other := ifelse(gender == 3 | gender == 4, 1, 0)]
  df[, college_educated := ifelse(education > 4, 1, 0)]
  df[, not_caucasian := ifelse(ethnicity != 3, 1, 0)]
  df[, age_under_40 := ifelse(age < 4, 1, 0)]
  df[, age_40_60 := ifelse(age > 4 & age <= 6, 1, 0)]
  df[, age_over_60 := ifelse(age >= 7, 1, 0)]
  df[, party_republican := ifelse(political_party == 1, 1, 0)]
  df[, party_democrat := ifelse(political_party == 2, 1, 0)]
  df[, party_other := ifelse(political_party == 3 | political_party == 4, 1, 0)]
  df[, party_non_republican := ifelse( political_party == 1, 0, 1)]
  df[, treatment_assignment := condition]
  df[, state_name :=  state_ordinals[state, V1]]
  df[, region:= state_ordinals[state, region]]
  df[, region_northeast := ifelse(region == 'northeast', 1,0)]
  df[, region_midwest   := ifelse(region == 'midwest', 1,0)]
  df[, region_south     := ifelse(region == 'south', 1,0)]
  df[, region_west      := ifelse(region == 'west', 1,0)]
  df[, region_other     := ifelse(region == 'other', 1,0)]
  
}

aggregate_covariates(run1)
aggregate_covariates(run2)
aggregate_covariates(combined)

head(combined[, c('state', 'state_name', 'region', 'region_northeast', 'region_midwest')])

```


```{r}
nrow(combined[covid_died == 1,])
```

```{r}
run_regression_outcome1_simplified = function(d, control_for_run=FALSE) {
  model_spread = lm(outcome_spread ~ treatment_assignment, d) 
  if (control_for_run) {
    model_spread_adv = lm(outcome_spread ~ treatment_assignment 
                       + run
                       + gender_female
                       + gender_other 
                       + age_40_60
                       + age_over_60
                       + party_democrat
                       + party_other
                       + not_caucasian
                       + college_educated
                       + region_south
                       + region_midwest
                       + region_west
                       + covid_sick 
                       + covid_hospitalized 
                       + covid_died, d)
    
  } else {
    model_spread_adv = lm(outcome_spread ~ treatment_assignment 
                       + gender_female
                       + gender_other
                       + age_under_40
                       + age_40_60
                       + age_over_60
                       + party_democrat
                       + party_other
                       + not_caucasian
                       + college_educated
                       + region_south
                       + region_midwest
                       + region_west
                       + covid_sick
                       + covid_hospitalized
                       + covid_died, d)
  }
  est_spread     = get_regression_results_robust_se(model_spread,  d, c('treatment_assignment'), FALSE)
  est_spread_adv = get_regression_results_robust_se(model_spread_adv, d, c('treatment_assignment'), FALSE)
  return ( list('model'= model_spread, 
                'model_adv'=model_spread_adv, 
                'est'=est_spread, 
                'est_adv'=est_spread_adv))
}

run_regression_outcome2_simplified = function(d, control_for_run=FALSE) {
  model_spread = lm(outcome_spread ~ treatment_assignment, d) 
  if (control_for_run) {
    model_spread_adv = lm(outcome_death ~ treatment_assignment 
                       + run
                       + gender_female
                       + gender_other
                       + age_40_60
                       + age_over_60
                       + party_democrat
                       + party_other
                       + not_caucasian
                       + college_educated
                       + region_south
                       + region_midwest
                       + region_west
                       + covid_sick 
                       + covid_hospitalized 
                       + covid_died, d)
    
  } else {
    model_spread_adv = lm(outcome_death ~ treatment_assignment 
                       + gender_female
                       + gender_other
                       + age_40_60
                       + age_over_60
                       + party_democrat
                       + party_other
                       + not_caucasian
                       + college_educated
                       + region_south
                       + region_midwest
                       + region_west
                       + covid_sick 
                       + covid_hospitalized 
                       + covid_died, d)
  }
  est_spread     = get_regression_results_robust_se(model_spread,  d, c('treatment_assignment'), FALSE)
  est_spread_adv = get_regression_results_robust_se(model_spread_adv, d, c('treatment_assignment'), FALSE)
  return ( list('model'= model_spread, 
                'model_adv'=model_spread_adv, 
                'est'=est_spread, 
                'est_adv'=est_spread_adv))
}

```


```{r}




mi_spread_run1 = run_regression_outcome1_simplified(run1, TRUE)
mi_spread_run2 = run_regression_outcome1_simplified(run2, TRUE)
mi_spread_combined_run = run_regression_outcome1_simplified(combined, TRUE)


stargazer(mi_spread_run1$model, mi_spread_run1$model_adv, 
          mi_spread_run2$model_adv, 
          mi_spread_combined_run$model_adv,
          type="text",  out="output/model1_regression.html", report="vcsp*",
          se = list(mi_spread_run1$est$robust_se_all, mi_spread_run1$est_adv$robust_se_all,
                    mi_spread_run2$est_adv$robust_se_all,
                    mi_spread_combined_run$est_adv$robust_se_all),
          title=paste('Concerned over COVID-19 Spread in U.S.'), 
          dep.var.caption  = "Concerned over COVID-19 Spread in U.S.",
          dep.var.labels.include = FALSE, model.numbers=FALSE,
          column.labels = c("July 21, 2020", "July 21, 2020", "July 25, 2020", "Both dates"),
          align=TRUE)



mi_spread_run1 = run_regression_outcome2_simplified(run1, TRUE)
mi_spread_run2 = run_regression_outcome2_simplified(run2, TRUE)
mi_spread_combined_run = run_regression_outcome2_simplified(combined, TRUE)


stargazer(mi_spread_run1$model, mi_spread_run1$model_adv, 
          mi_spread_run2$model_adv, 
          mi_spread_combined_run$model_adv,
          type="html",  out="output/model2_regression.html", report="vcsp*",
          se = list(mi_spread_run1$est$robust_se_all, mi_spread_run1$est_adv$robust_se_all,
                    mi_spread_run2$est_adv$robust_se_all,
                    mi_spread_combined_run$est_adv$robust_se_all),
          title=paste('Distressed by COVID-19 Deaths in U.S.'), 
          dep.var.caption  = "Distressed by COVID-19 Deaths in U.S.",
          dep.var.labels.include = FALSE, model.numbers=FALSE,
          column.labels = c("July 21, 2020", "July 21, 2020", "July 25, 2020", "Both dates"),
          align=TRUE)
```




```{r}
run_regression_outcome1_hte = function(d) {
  
    model_spread_adv = lm(outcome_spread ~ treatment_assignment 
                       + gender_female
                       + gender_other
                       + age_40_60
                       + age_over_60
                       + party_democrat
                       + party_other
                       + party_other:treatment_assignment
                       + not_caucasian
                       + college_educated
                       + region_south
                       + region_midwest
                       + region_west
                       + covid_sick 
                       + covid_hospitalized 
                       + covid_died, d)

  est_spread_adv = get_regression_results_robust_se(model_spread_adv, d, c('treatment_assignment'), FALSE)
  return ( list('model_adv'=model_spread_adv, 
                'est_adv'=est_spread_adv))
}

run_regression_outcome2_hte = function(d) {
  
    model_spread_adv = lm(outcome_death ~ treatment_assignment 
                       + gender_female
                       + gender_other
                       + age_40_60
                       + age_over_60
                       + party_democrat
                       + party_other
                       + party_other:treatment_assignment
                       + not_caucasian
                       + college_educated
                       + region_south
                       + region_midwest
                       + region_west
                       + covid_sick 
                       + covid_hospitalized 
                       + covid_died, d)

  est_spread_adv = get_regression_results_robust_se(model_spread_adv, d, c('treatment_assignment'), FALSE)
  return ( list('model_adv'=model_spread_adv, 
                'est_adv'=est_spread_adv))
}


```

```{r}




mi_spread_combined_run = run_regression_outcome1_hte(combined)
mi_death_combined_run  = run_regression_outcome2_hte(combined)


stargazer(mi_spread_combined_run$model_adv, 
          #type = "text",
          type="html",  out="output/model_combined_spread_hte_regression.html", report="vcsp*",
          se = list(mi_spread_combined_run$est_adv$robust_se_all),
          dep.var.caption  = "Concerned over COVID-19 Spread in U.S. - HTE",
          dep.var.labels.include = FALSE, model.numbers=FALSE,
          column.labels = c("Both dates"),
          align=TRUE)


stargazer(mi_death_combined_run$model_adv, 
          #type = "text",
          type="html",  out="output/model_combined_death_hte_regression.html", report="vcsp*",
          se = list(mi_death_combined_run$est_adv$robust_se_all),
          dep.var.caption  = "Distressed by COVID-19 Spread in U.S. - HTE",
          dep.var.labels.include = FALSE, model.numbers=FALSE,
          column.labels = c("Both dates"),
          align=TRUE)
```

```{r}
t.test(gender ~ treatment_assignment, data = run2)
t.test(age ~ treatment_assignment, data = run2)
t.test(age_under_40  ~ treatment_assignment, data = run2)
t.test(political_party ~ treatment_assignment, data = run2)
t.test(ethnicity ~ treatment_assignment, data = run2)
t.test(state ~ treatment_assignment, data = run2)
t.test(college_educated ~ treatment_assignment, data = run2)
t.test(covid_sick ~ treatment_assignment, data = run2)
t.test(covid_hospitalized ~ treatment_assignment, data = run2)
t.test(covid_died ~ treatment_assignment, data = run2)


```
```{r}
t.test(party_republican ~ treatment_assignment, data = run2)
t.test(party_democrat ~ treatment_assignment, data = run2)
t.test(party_other ~ treatment_assignment, data = run2)

```